# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sgd.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sgd.proto',
  package='stochastic',
  syntax='proto3',
  serialized_pb=_b('\n\tsgd.proto\x12\nstochastic\"\xb0\x01\n\x03LWB\x12\x0e\n\x06labels\x18\x01 \x01(\x05\x12\x0f\n\x07weights\x18\x02 \x03(\x02\x12)\n\x05\x62\x61tch\x18\x03 \x03(\x0b\x32\x1a.stochastic.LWB.BatchEntry\x12\x0e\n\x06\x63orr_1\x18\x04 \x01(\x02\x12\x0e\n\x06\x63orr_2\x18\x05 \x01(\x02\x12\x0f\n\x07lambda_\x18\x06 \x01(\x02\x1a,\n\nBatchEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"h\n\x06Update\x12/\n\x07grad_up\x18\x01 \x03(\x0b\x32\x1e.stochastic.Update.GradUpEntry\x1a-\n\x0bGradUpEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32;\n\x03SGD\x12\x34\n\x0b\x43omputeTask\x12\x0f.stochastic.LWB\x1a\x12.stochastic.Update\"\x00\x62\x06proto3')
)




_LWB_BATCHENTRY = _descriptor.Descriptor(
  name='BatchEntry',
  full_name='stochastic.LWB.BatchEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='stochastic.LWB.BatchEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='stochastic.LWB.BatchEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=202,
)

_LWB = _descriptor.Descriptor(
  name='LWB',
  full_name='stochastic.LWB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='labels', full_name='stochastic.LWB.labels', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weights', full_name='stochastic.LWB.weights', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batch', full_name='stochastic.LWB.batch', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='corr_1', full_name='stochastic.LWB.corr_1', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='corr_2', full_name='stochastic.LWB.corr_2', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lambda_', full_name='stochastic.LWB.lambda_', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LWB_BATCHENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=202,
)


_UPDATE_GRADUPENTRY = _descriptor.Descriptor(
  name='GradUpEntry',
  full_name='stochastic.Update.GradUpEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='stochastic.Update.GradUpEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='stochastic.Update.GradUpEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=308,
)

_UPDATE = _descriptor.Descriptor(
  name='Update',
  full_name='stochastic.Update',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='grad_up', full_name='stochastic.Update.grad_up', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_UPDATE_GRADUPENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=308,
)

_LWB_BATCHENTRY.containing_type = _LWB
_LWB.fields_by_name['batch'].message_type = _LWB_BATCHENTRY
_UPDATE_GRADUPENTRY.containing_type = _UPDATE
_UPDATE.fields_by_name['grad_up'].message_type = _UPDATE_GRADUPENTRY
DESCRIPTOR.message_types_by_name['LWB'] = _LWB
DESCRIPTOR.message_types_by_name['Update'] = _UPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LWB = _reflection.GeneratedProtocolMessageType('LWB', (_message.Message,), dict(

  BatchEntry = _reflection.GeneratedProtocolMessageType('BatchEntry', (_message.Message,), dict(
    DESCRIPTOR = _LWB_BATCHENTRY,
    __module__ = 'sgd_pb2'
    # @@protoc_insertion_point(class_scope:stochastic.LWB.BatchEntry)
    ))
  ,
  DESCRIPTOR = _LWB,
  __module__ = 'sgd_pb2'
  # @@protoc_insertion_point(class_scope:stochastic.LWB)
  ))
_sym_db.RegisterMessage(LWB)
_sym_db.RegisterMessage(LWB.BatchEntry)

Update = _reflection.GeneratedProtocolMessageType('Update', (_message.Message,), dict(

  GradUpEntry = _reflection.GeneratedProtocolMessageType('GradUpEntry', (_message.Message,), dict(
    DESCRIPTOR = _UPDATE_GRADUPENTRY,
    __module__ = 'sgd_pb2'
    # @@protoc_insertion_point(class_scope:stochastic.Update.GradUpEntry)
    ))
  ,
  DESCRIPTOR = _UPDATE,
  __module__ = 'sgd_pb2'
  # @@protoc_insertion_point(class_scope:stochastic.Update)
  ))
_sym_db.RegisterMessage(Update)
_sym_db.RegisterMessage(Update.GradUpEntry)


_LWB_BATCHENTRY.has_options = True
_LWB_BATCHENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_UPDATE_GRADUPENTRY.has_options = True
_UPDATE_GRADUPENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))

_SGD = _descriptor.ServiceDescriptor(
  name='SGD',
  full_name='stochastic.SGD',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=310,
  serialized_end=369,
  methods=[
  _descriptor.MethodDescriptor(
    name='ComputeTask',
    full_name='stochastic.SGD.ComputeTask',
    index=0,
    containing_service=None,
    input_type=_LWB,
    output_type=_UPDATE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SGD)

DESCRIPTOR.services_by_name['SGD'] = _SGD

# @@protoc_insertion_point(module_scope)
